FROM python:3

ARG ARANGO_USERNAME
ARG ARANGO_PASSWORD
ARG JWT_SECRET_KEY

ARG VERSION
ARG JOB_URL
ARG COMMIT_SHA



ENV ARANGO_USERNAME=$ARANGO_USERNAME
ENV ARANGO_PASSWORD=$ARANGO_PASSWORD
ENV JWT_SECRET_KEY=$JWT_SECRET_KEY

ENV VERSION=$VERSION
ENV JOB_URL=$JOB_URL
ENV COMMIT_SHA=$COMMIT_SHA

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD [ "python", "./main.py" ]

